### ISSUE TITLE
Error when installing globally

### ISSUE THREAD

**Issue by EricCrosson** [typescript-tools/rust-implementation#34]
To reproduce: `npm install -g @typescript-tools/rust-implementation`

Produces something like
```
Uncaught SyntaxError: Unexpected identifier
> curl https://github.com/typescript-tools/rust-implementation/releases/download/v1.2.1/typescript-tools-x86_64-apple-darwin.tar.gz
; npm i -g @typescript-tools/rust-implementation
/Users/ericcrosson/.local/opt/nvm/versions/node/v14.16.0/bin/monorepo -> /Users/ericcrosson/.local/opt/nvm/versions/node/v14.16.0/lib/node_modules/@typescript-tools/rust-implementation/bin/monorepo

> @typescript-tools/rust-implementation@2.0.10 postinstall /Users/ericcrosson/.local/opt/nvm/versions/node/v14.16.0/lib/node_modules/@typescript-tools/rust-implementation
> node npm/install.js

(node:57085) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, link '/Users/ericcrosson/.local/opt/nvm/versions/node/v14.16.0/lib/node_modules/@typescript-tools/rust-implementation/bin/monorepo' -> '/Users/ericcrosson/.local/opt/nvm/versions/node/v14.16.0/lib/node_modules/.bin/tmp-57085-mcXIaxkJLk2i'
    at Object.linkSync (fs.js:1194:3)
    at linkBinaryIntoBin (/Users/ericcrosson/.local/opt/nvm/versions/node/v14.16.0/lib/node_modules/@typescript-tools/rust-implementation/npm/install.js:23:6)
```

(this collected from macos)

**Comment by EricCrosson** [comment]
Note that installation is still functional

**Comment by EricCrosson** [comment]
npm is no longer a distribution channel
